# docker-compose.yml
version: '3.8'

services:
  # --- Architecture A: Monolithic HTTP Cluster ---
  http-node1:
    build: .
    command: python http_server.py
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - OTHER_NODES=http://http-node2:5000,http://http-node3:5000,http://http-node4:5000,http://http-node5:5000
  
  http-node2:
    build: .
    command: python http_server.py
    environment:
      - PORT=5000
      - OTHER_NODES=http://http-node1:5000,http://http-node3:5000,http://http-node4:5000,http://http-node5:5000

  http-node3:
    build: .
    command: python http_server.py
    environment:
      - PORT=5000
      - OTHER_NODES=http://http-node1:5000,http://http-node2:5000,http://http-node4:5000,http://http-node5:5000

  http-node4:
    build: .
    command: python http_server.py
    environment:
      - PORT=5000
      - OTHER_NODES=http://http-node1:5000,http://http-node2:5000,http://http-node3:5000,http://http-node5:5000

  http-node5:
    build: .
    command: python http_server.py
    environment:
      - PORT=5000
      - OTHER_NODES=http://http-node1:5000,http://http-node2:5000,http://http-node3:5000,http://http-node4:5000

  # --- Architecture B: Microservices gRPC Cluster ---
  grpc-node1:
    build: .
    command: python grpc_server.py
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - OTHER_NODES_ADDR=grpc-node2:50051,grpc-node3:50051,grpc-node4:50051,grpc-node5:50051
  
  grpc-node2:
    build: .
    command: python grpc_server.py
    environment:
      - PORT=50051
      - OTHER_NODES_ADDR=grpc-node1:50051,grpc-node3:50051,grpc-node4:50051,grpc-node5:50051

  grpc-node3:
    build: .
    command: python grpc_server.py
    environment:
      - PORT=50051
      - OTHER_NODES_ADDR=grpc-node1:50051,grpc-node2:50051,grpc-node4:50051,grpc-node5:50051

  grpc-node4:
    build: .
    command: python grpc_server.py
    environment:
      - PORT=50051
      - OTHER_NODES_ADDR=grpc-node1:50051,grpc-node2:50051,grpc-node3:50051,grpc-node5:50051

  grpc-node5:
    build: .
    command: python grpc_server.py
    environment:
      - PORT=50051
      - OTHER_NODES_ADDR=grpc-node1:50051,grpc-node2:50051,grpc-node3:50051,grpc-node4:50051