# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vault_pb2 as vault__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vault_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VaultServiceStub(object):
    """The service definition for the password vault
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.AddSecret = channel.unary_unary(
                '/vault.VaultService/AddSecret',
                request_serializer=vault__pb2.AddSecretRequest.SerializeToString,
                response_deserializer=vault__pb2.AddSecretResponse.FromString,
                _registered_method=True)
        self.RetrieveSecret = channel.unary_unary(
                '/vault.VaultService/RetrieveSecret',
                request_serializer=vault__pb2.RetrieveSecretRequest.SerializeToString,
                response_deserializer=vault__pb2.RetrieveSecretResponse.FromString,
                _registered_method=True)
        self.ReplicateSecret = channel.unary_unary(
                '/vault.VaultService/ReplicateSecret',
                request_serializer=vault__pb2.ReplicateSecretRequest.SerializeToString,
                response_deserializer=vault__pb2.ReplicateSecretResponse.FromString,
                _registered_method=True)


class VaultServiceServicer(object):
    """The service definition for the password vault
    """

    def AddSecret(self, request, context):
        """Adds a secret to the vault and triggers replication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RetrieveSecret(self, request, context):
        """Retrieves a secret from the vault
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateSecret(self, request, context):
        """Internal RPC for replication
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VaultServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'AddSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.AddSecret,
                    request_deserializer=vault__pb2.AddSecretRequest.FromString,
                    response_serializer=vault__pb2.AddSecretResponse.SerializeToString,
            ),
            'RetrieveSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.RetrieveSecret,
                    request_deserializer=vault__pb2.RetrieveSecretRequest.FromString,
                    response_serializer=vault__pb2.RetrieveSecretResponse.SerializeToString,
            ),
            'ReplicateSecret': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateSecret,
                    request_deserializer=vault__pb2.ReplicateSecretRequest.FromString,
                    response_serializer=vault__pb2.ReplicateSecretResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vault.VaultService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vault.VaultService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VaultService(object):
    """The service definition for the password vault
    """

    @staticmethod
    def AddSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault.VaultService/AddSecret',
            vault__pb2.AddSecretRequest.SerializeToString,
            vault__pb2.AddSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RetrieveSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault.VaultService/RetrieveSecret',
            vault__pb2.RetrieveSecretRequest.SerializeToString,
            vault__pb2.RetrieveSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateSecret(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vault.VaultService/ReplicateSecret',
            vault__pb2.ReplicateSecretRequest.SerializeToString,
            vault__pb2.ReplicateSecretResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
