# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vault.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'vault.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bvault.proto\x12\x05vault\",\n\x10\x41\x64\x64SecretRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"0\n\x11\x41\x64\x64SecretResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\"#\n\x15RetrieveSecretRequest\x12\n\n\x02id\x18\x01 \x01(\t\"2\n\x16RetrieveSecretResponse\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"2\n\x16ReplicateSecretRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"*\n\x17ReplicateSecretResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xf5\x01\n\x0cVaultService\x12@\n\tAddSecret\x12\x17.vault.AddSecretRequest\x1a\x18.vault.AddSecretResponse\"\x00\x12O\n\x0eRetrieveSecret\x12\x1c.vault.RetrieveSecretRequest\x1a\x1d.vault.RetrieveSecretResponse\"\x00\x12R\n\x0fReplicateSecret\x12\x1d.vault.ReplicateSecretRequest\x1a\x1e.vault.ReplicateSecretResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vault_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ADDSECRETREQUEST']._serialized_start=22
  _globals['_ADDSECRETREQUEST']._serialized_end=66
  _globals['_ADDSECRETRESPONSE']._serialized_start=68
  _globals['_ADDSECRETRESPONSE']._serialized_end=116
  _globals['_RETRIEVESECRETREQUEST']._serialized_start=118
  _globals['_RETRIEVESECRETREQUEST']._serialized_end=153
  _globals['_RETRIEVESECRETRESPONSE']._serialized_start=155
  _globals['_RETRIEVESECRETRESPONSE']._serialized_end=205
  _globals['_REPLICATESECRETREQUEST']._serialized_start=207
  _globals['_REPLICATESECRETREQUEST']._serialized_end=257
  _globals['_REPLICATESECRETRESPONSE']._serialized_start=259
  _globals['_REPLICATESECRETRESPONSE']._serialized_end=301
  _globals['_VAULTSERVICE']._serialized_start=304
  _globals['_VAULTSERVICE']._serialized_end=549
# @@protoc_insertion_point(module_scope)
